after_success:
- cp $TRAVIS_BUILD_DIR/src/Clients/build/libs/*.war $TRAVIS_BUILD_DIR/deploy/docker/Clients/drop/
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=p1gps
- export TAG=web
- docker build -t $REPO/$TAG $TRAVIS_BUILD_DIR/deploy/docker/Clients
- docker tag $REPO/$TAG $DOCKER_USER/$REPO:$TAG
- docker push $DOCKER_USER/$REPO:$TAG
- cp $TRAVIS_BUILD_DIR/src/Backend/OrderService/build/libs/ordering* $TRAVIS_BUILD_DIR/deploy/docker/Order/drop/
- export TAG=order
- docker build -t $REPO/$TAG $TRAVIS_BUILD_DIR/deploy/docker/Order
- docker tag $REPO/$TAG $DOCKER_USER/$REPO:$TAG
- docker push $DOCKER_USER/$REPO:$TAG
